### PR TITLE
Fix available resources is always zero after kubelet restart

### PR DESCRIPTION
**Pull request by miaojianwei**
This PR is to resolve issue #48 .

There are two problems in ListAndWatch function:

1. RDMA resources change to 0 after kubelet restart, and will not be updated again.

    Because the ListAndWatch stream is closed but the ListAndWatch function may be still running, after kubelet restart, the new ListAndWatch function will invoke `rs.updateResource <- true`, but this message is consumed by the old ListAndWatch function, old ListAndWatch function fail to send devices to kubelet because the old stream has been closed,  so the rdma resourcs in node status remain to be 0, since devices is not changed,  so the device plugin won't generate update evnets any more.

    **Solution:**
    When `stream.Send` fail, return an error to stop old ListAndWatch function, and pass the update event to the new ListAndWatch function for processing.

2. ListAndWatch function may be blocked  in `rs.updateResource <- true` forever.

    During kubelet restart, if devices change,  `rs.updateResource <- true` will be called in UpdateDevices function, so when kubelet begin to ListAndWatch, this function will be blocked  in `rs.updateResource <- true` forever.

    **Solution:**
    Don't use `rs.updateResource <- true` at the begin of ListAndWatch,  use `s.Send` instead.

### CODE REVIEW

**Comment by adrianchiris** [comment]
Hey there, Thank you for contributing !

The change looks good to me, mind squashing you two commits into one and reformating commit message according to:

https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines

**Review by e0ne — APPROVED** [review]
LGTM, thanks for your contribution, @miaojianwei!

**Comment by miaojianwei** [comment]
> Hey there, Thank you for contributing !
> 
> The change looks good to me, mind squashing you two commits into one and reformatting commit message according to:
> 
> https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines

Thank you for your suggestion. 

I have squashed commits and changed the commit message, please check it again.

**Comment by howels** [comment]
Please consider pushing a new release to make this fix more widely available.

**Pull request merged**
