### PR TITLE
Make k8s-rdma-shared-dev-plugin base image configurable

### PR DESCRIPTION
**Pull request by e0ne**
Signed-off-by: Ivan Kolodyazhny <ikolodiazhny@nvidia.com>

### CODE REVIEW

**Review by e0ne — COMMENTED** [review]
Need to update make target to build UBI-based image

**Comment by moshe010** [comment]
how will you push images to docker hub UBI and alpine?

**Comment by e0ne** [comment]
> how will you push images to docker hub UBI and alpine?

It's a good question.  We can use different labels (e.g. k8s-rdma-shared-dev-plugin:ubi-latest) or image name (e.g. k8s-rdma-shared-dev-plugin-ubi:latest)

**Comment by moshe010** [comment]
> > how will you push images to docker hub UBI and alpine?
> 
> It's a good question. We can use different labels (e.g. k8s-rdma-shared-dev-plugin:ubi-latest) or image name (e.g. k8s-rdma-shared-dev-plugin-ubi:latest)

but I want it to by automatically pushed to dockerhub.

**Review by moshe010 — APPROVED** [review]

**Pull request merged**
